name: CI/CD

on:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches: 
    - main
    - develop
    
jobs:

  ci-cd:
    runs-on: self-hosted
    steps:
      # Step 1      
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
          architecture: x64
 # Step 3
      - name: Install Python Virtual ENV
        run: pip3 install virtualenv
      # Step 4
      - name:  Setup Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      # Step 5
      - name: Activate and Install Dependencies into Virtual env
        run: python3 -m venv venv && source venv/bin/activate &&
          pip3 install -r app/requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      # Step 6     
      - name: Activate venv and Run Tests     
        run: . venv/bin/activate && pytest
      # Step 7
      - name: Build Docker-compose
        run: docker-compose build
      # Step 8
      - name: Run Docker-compose servies
        run: docker-compose up -d

